version: "3"
services:
  nginx:
    image: nginx:1.17.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./set-certbot.sh:/usr/local/bin/set-certbot.sh
    networks:
      default:
        ipv4_address: 192.168.148.3
    command: sh -c "/usr/local/bin/set-certbot.sh"
networks:
  default:
    external:
      name: br_192.168.148.1